name: Build and deploy to GCP

on:
  push:
    branches: [main]

env:
  PROJECT_ID: second-terra-452922-p7
  IMAGE_NAME: instance-grp-front-end

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Docker auth for GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
